[2021-05-25 07:58:57] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['xch4', 'model_xco2_range'], region=[173.94959, 33.87985, 194.94959, 54.87985])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 396, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 437, in get_dataset_xy_names
    return (_get_coord_var_name(dataset, x_name, X_COORD_VAR_NAMES, 'x'),
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'x'-coordinate variable in dataset
[2021-05-25 11:44:38] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['xch4_quality_flag', 'longitude'], region=[69.56768, -41.80962, 90.56768, -20.80962])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 399, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 438, in get_dataset_xy_names
    _get_coord_var_name(dataset, y_name, Y_COORD_VAR_NAMES, 'y'))
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'y'-coordinate variable in dataset
[2021-05-25 11:56:14] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['xco2_averaging_kernel', 'solar_zenith_angle'], region=[174.89797, -8.06882, 195.89797, 12.93118])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 396, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 437, in get_dataset_xy_names
    return (_get_coord_var_name(dataset, x_name, X_COORD_VAR_NAMES, 'x'),
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'x'-coordinate variable in dataset
[2021-05-25 12:05:28] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['xco2_averaging_kernel', 'raw_xch4'], region=[1.03379, -22.50298, 22.03379, -1.50298])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 396, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 437, in get_dataset_xy_names
    return (_get_coord_var_name(dataset, x_name, X_COORD_VAR_NAMES, 'x'),
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'x'-coordinate variable in dataset
