[2021-05-25 08:03:55] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.RA-2.Envisat.NH25KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['status_flag', 'sea_ice_thickness'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-25 11:49:27] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.RA-2.Envisat.NH25KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['sea_ice_thickness_uncertainty', 'lat'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 358, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-25 12:00:59] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.RA-2.Envisat.NH25KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['status_flag', 'freeboard_uncertainty'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-25 12:10:20] Request: 
open_dataset(ds_id=esacci.SEAICE.mon.L3C.SITHICK.RA-2.Envisat.NH25KMEASE2.2-0.r1, store_id=cci-store, time_range=None, var_names=['sea_ice_thickness', 'sea_ice_thickness'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
