[2021-05-25 07:58:21] Request: 
open_dataset(ds_id=esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.3-0.r1, store_id=cci-store, time_range=None, var_names=['cla_vis006', 'cth_std'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-25 11:43:56] Request: 
open_dataset(ds_id=esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.3-0.r1, store_id=cci-store, time_range=None, var_names=['cfc_high', 'nobs_cloudy_day'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 345, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 436, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 485, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 249, in open_data
    ds = self._normalize_dataset(ds, cci_schema, **open_params)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 297, in _normalize_dataset
    ds = cubify_dataset(ds)
  File "/home/users/tfincke/Projects/xcube/xcube/core/normalize.py", line 48, in cubify_dataset
    return assert_cube(ds)
  File "/home/users/tfincke/Projects/xcube/xcube/core/verify.py", line 44, in assert_cube
    raise ValueError(message)
ValueError: Dataset is not a valid xcube dataset, because:
- all data variables must have same chunk sizes, but found ((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), (360,), (720,)) for 'cfc_high' and ((203,), (360,), (720,)) for 'nobs_cloudy_day'.
[2021-05-25 11:55:35] Request: 
open_dataset(ds_id=esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.3-0.r1, store_id=cci-store, time_range=None, var_names=['cth_corr_unc', 'cth_corr_unc'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-25 12:04:49] Request: 
open_dataset(ds_id=esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.3-0.r1, store_id=cci-store, time_range=None, var_names=['cot_prop_unc', 'lwp_allsky'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 355, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
