[2021-06-10 10:20:06] Request: 
open_dataset(ds_id=esacci.AEROSOL.day.L3C.AOD.MERIS.Envisat.MERIS_ENVISAT.2-2.r1, store_id=cci-store, time_range=None, var_names=['R_eff_std', 'AOD865'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 356, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 436, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 485, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 245, in open_data
    chunk_store = CciChunkStore(self._cci_odp, data_id, cube_kwargs)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 661, in __init__
    super().__init__(dataset_id,
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 197, in __init__
    sizes.append(self._dimension_data[dimension_name]['size'])
KeyError: 'latitude'
[2021-06-10 10:40:02] Request: 
open_dataset(ds_id=esacci.AEROSOL.day.L3C.AOD.MERIS.Envisat.MERIS_ENVISAT.2-2.r1, store_id=cci-store, time_range=None, var_names=['R_eff', 'R_eff'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 356, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 436, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 485, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 245, in open_data
    chunk_store = CciChunkStore(self._cci_odp, data_id, cube_kwargs)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 661, in __init__
    super().__init__(dataset_id,
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 197, in __init__
    sizes.append(self._dimension_data[dimension_name]['size'])
KeyError: 'latitude'
[2021-06-10 10:47:04] Request: 
open_dataset(ds_id=esacci.AEROSOL.day.L3C.AOD.MERIS.Envisat.MERIS_ENVISAT.2-2.r1, store_id=cci-store, time_range=None, var_names=['fAOD865', 'AOD865_std'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 356, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 436, in open_dataset
    dataset = data_store.open_data(data_id=dataset_id, opener_id=opener_id, **open_args)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 485, in open_data
    return self._get_opener(opener_id=opener_id).open_data(data_id, **open_params)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/dataaccess.py", line 245, in open_data
    chunk_store = CciChunkStore(self._cci_odp, data_id, cube_kwargs)
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 661, in __init__
    super().__init__(dataset_id,
  File "/home/users/tfincke/Projects/xcube-cci/xcube_cci/chunkstore.py", line 197, in __init__
    sizes.append(self._dimension_data[dimension_name]['size'])
KeyError: 'latitude'
