[2021-05-12 16:31:30] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['h2o_profile_apriori', 'raw_xch4'], region=[-139.38489, 46.64162, -118.38489, 67.64162])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 395, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 437, in get_dataset_xy_names
    return (_get_coord_var_name(dataset, x_name, X_COORD_VAR_NAMES, 'x'),
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'x'-coordinate variable in dataset
[2021-05-12 16:56:29] Request: 
open_dataset(ds_id=esacci.GHG.satellite-orbit-frequency.L2.CH4.TANSO-FTS.GOSAT.OCPR.v7-0.r1, store_id=cci-store, time_range=None, var_names=['gain', 'raw_xch4_error'], region=[-174.89798, -8.45643, -153.89798, 12.54357])

Traceback (most recent call last):
  File "test_cci_data_support.py", line 395, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/users/tfincke/Projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 438, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 37, in select_subset
    dataset = select_spatial_subset(dataset, xy_bbox=bbox)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 86, in select_spatial_subset
    x_name, y_name = get_dataset_xy_names(dataset, xy_names=xy_names)
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 437, in get_dataset_xy_names
    return (_get_coord_var_name(dataset, x_name, X_COORD_VAR_NAMES, 'x'),
  File "/home/users/tfincke/Projects/xcube/xcube/core/geocoding.py", line 447, in _get_coord_var_name
    raise ValueError(f'cannot detect {dim_name!r}-coordinate variable in dataset')
ValueError: cannot detect 'x'-coordinate variable in dataset
