[2021-12-21 12:22:05] Request: 
open_dataset(ds_id=ESACCI-GHG-L2-CO2-SCIAMACHY-WFMD-2002-2012-fv1.zarr, store_id=cci-zarr-store, time_range=('2007-07-05', '2007-07-05'), var_names=['scene_number', 'solar_zenith_angle'], region=None)

Traceback (most recent call last):
  File "/home/xcube/projects/cate-e2e/testing-cci-datasets/test_cci_data_support.py", line 401, in test_open_ds
    dataset = open_dataset(ds_id=data_id,
  File "/home/xcube/projects/cate/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/home/xcube/projects/cate/cate/ops/io.py", line 85, in open_dataset
    ds, ds_id = cate.core.ds.open_dataset(dataset_id=ds_id,
  File "/home/xcube/projects/cate/cate/core/ds.py", line 452, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/xcube/miniconda3/envs/cate-env-development/lib/python3.9/site-packages/xcube/core/select.py", line 66, in select_subset
    dataset = select_temporal_subset(dataset, time_range=time_range)
  File "/home/xcube/miniconda3/envs/cate-env-development/lib/python3.9/site-packages/xcube/core/select.py", line 195, in select_temporal_subset
    raise ValueError(f'cannot compute temporal subset: variable'
ValueError: cannot compute temporal subset: variable "time" not found in dataset
